config/routes.rb
DeltaChan::Application.routes.draw do

  namespace :admin do
    root to: "dashboard#index"
    resource :session, only: [:new, :create, :destroy]
    resources :users, only: [:new, :create, :destroy, :index]
    resources :sections
  end

  root to: "main#index"

  resources :messages, only: [:show, :create]

  resources :sections, path: '', only: [:show] do
    resources :topics, only: [:show, :create]
  end

end

app/models/admin_user.rb
class AdminUser < ActiveRecord::Base
  has_secure_password
  attr_accessible :email, :password

  validates_presence_of :email
  validates_uniqueness_of :email
end

app/models/message.rb
class Message < ActiveRecord::Base
  belongs_to :topic
  attr_accessible :author, :image, :message, :topic, :topic_id

  has_attached_file :image, :styles => { :thumb => "200x200>" }

  validates :message, :presence => true
  validates :topic_id, :numericality => { :only_integer => true }

  default_scope order('created_at ASC')
end

app/models/section.rb
class Section < ActiveRecord::Base
  attr_accessible :description, :position, :slug, :title

  validates :description, :slug, :title, :presence => true
  validates :position, :numericality => { :only_integer => true }
end

app/models/topic.rb
class Topic < ActiveRecord::Base
  belongs_to :section
  has_many :messages
  attr_accessible :author, :message, :title, :image, :section_id
  has_attached_file :image, :styles => { :thumb => "200x200>" }

  validates :message, :title, :presence => true
  validates :section_id, :numericality => { :only_integer => true }

  default_scope order('created_at DESC')
end

app/controllers/admin/dashboard_controller.rb
class Admin::DashboardController < ApplicationController
  layout 'admin'

  before_filter :check_auth

  def index
  end
end

app/controllers/admin/sections_controller.rb
class Admin::SectionsController < Admin::DashboardController
  crudify :section

  def create
    @section = Section.new(params[:section])
    if @section.save
      flash[:notice] = "Section created"
      redirect_to admin_sections_path
    else
      render 'new'
    end
  end
end

app/controllers/admin/sessions_controller.rb
class Admin::SessionsController < Admin::DashboardController
  before_filter :check_auth, only: [:destroy]

  def new
  end

  def create
    user = AdminUser.find_by_email(params[:email])
    if user && user.authenticate(params[:password])
      session[:user_id] = user.id
      redirect_to admin_root_path, :notice => "Logged in!"
    else
      flash.now.alert = "Invalid email or password"
      render "new"
    end
  end

  def destroy
    session[:user_id] = nil
    redirect_to admin_root_path, :notice => "Logged out!"
  end
end

app/controllers/admin/users_controller.rb
class Admin::UsersController < Admin::DashboardController
  def index
    @users = AdminUser.all
  end

  def new
    @user = AdminUser.new
  end

  def create
    @user = AdminUser.new(params[:admin_user])
    if @user.save
      redirect_to admin_users_path
    else
      flash[:notice] = "Error saving user"
      redirect_to admin_users_path
    end
  end

  def destroy
    AdminUser.find(params[:id]).destroy
    flash[:notice] = "User destroyed"
    redirect_to admin_users_path
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery

  private

  def current_user
    begin
      @current_user ||= AdminUser.find(session[:user_id]) if session[:user_id]
    rescue
      nil
    end
  end

  def check_auth
    redirect_to new_admin_session_path unless current_user
  end

  helper_method :current_user
end

app/controllers/main_controller.rb
class MainController < ApplicationController
  def index
    @topics = Topic.limit(25)
  end
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
  def create
    @message = Message.new(params[:message])
    unless params[:image_url].empty?
      begin
        @message.image = URI.parse(URI.encode(params[:image_url]))
      rescue
        flash[:notice] = "Loading image from url failed!"
      end
    end
    if @message.save
      flash[:notice] = "Message created"
      redirect_to "/#{@message.topic.section.slug}/topics/#{@message.topic.id}"
    else
      render template: 'messages/new'
    end
  end

  def show
  end
end

app/controllers/sections_controller.rb
class SectionsController < ApplicationController

  def show
    @section = Section.find_by_slug(params[:id])
    @topic = Topic.new(section_id: @section.id)
    @topics = Topic.find_all_by_section_id(@section.id)
  end
end

app/controllers/topics_controller.rb
class TopicsController < ApplicationController

  def create
    @topic = Topic.new(params[:topic])
    unless params[:image_url].empty?
      begin
        @topic.image = URI.parse(URI.encode(params[:image_url]))
      rescue
        flash[:notice] = "Loading image from url failed!"
      end
    end
    if @topic.save
      flash[:notice] = "Topic created"
      redirect_to "/#{@topic.section.slug}"
    else
      @section = @topic.section
      render template: 'sections/show'
    end
  end

  def show
    @topic = Topic.find(params[:id])
    @message = Message.new(topic: @topic)
  end
end

app/helpers/admin/dashboard_helper.rb
module Admin::DashboardHelper
end

app/helpers/admin/sections_helper.rb
module Admin::SectionsHelper
end

app/helpers/admin/sessions_helper.rb
module Admin::SessionsHelper
end

app/helpers/admin/users_helper.rb
module Admin::UsersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper

  def sections
    Section.all
  end
end

app/helpers/main_helper.rb
module MainHelper
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/helpers/sections_helper.rb
module SectionsHelper
end

app/helpers/topics_helper.rb
module TopicsHelper
end

app/views/admin/dashboard/index.html.erb
<div class="row">
  <h1>Административный интерфейс</h1>
</div>

app/views/admin/sections/_form.html.erb
<% section.errors.full_messages.each do |msg| %>
  <div class="alert alert-error"><%= msg %></span></div>
<% end %>

<div class="control-group">
  <%= f.label :slug, class: "control-label" %>
  <div class="controls">
    <%= f.text_field :slug %>
  </div>
</div>

<div class="control-group">
  <%= f.label :title, class: "control-label" %>
  <div class="controls">
    <%= f.text_field :title %>
  </div>
</div>

<div class="control-group">
  <%= f.label :position, class: "control-label" %>
  <div class="controls">
    <%= f.text_field :position %>
  </div>
</div>

<div class="control-group">
  <%= f.label :description, class: "control-label" %>
  <div class="controls">
    <%= f.text_area :description %>
  </div>
</div>

app/views/admin/sections/create.html.erb
<h1>Admin::Sections#create</h1>
<p>Find me in app/views/admin/sections/create.html.erb</p>

app/views/admin/sections/destroy.html.erb
<h1>Admin::Sections#destroy</h1>
<p>Find me in app/views/admin/sections/destroy.html.erb</p>

app/views/admin/sections/edit.html.erb
<h1>Изменить раздел <%= @section.title %></h1>

<%= form_for @section, url: admin_section_path(@section), method: :put, html: {class: "form-horizontal"} do |f| %>

  <%= render 'form', section: @section, f: f %>

  <div class="control-group">
    <div class="controls">
      <%= f.submit "Изменить", class: "btn" %>
    </div>
  </div>
<% end %>

app/views/admin/sections/index.html.erb
<h1>Список разделов</h1>

<table class="table table-bordered">
  <thead>
    <tr>
      <th>URL (slug)</th>
      <th>Заголовок</th>
      <th>Действие</th>
    </tr>
  </thead>
  <tbody>
    <% @sections.each do |section| %>
      <tr>
        <td><%= section.slug %></td>
        <td><%= section.title %></td>
        <td>
          <%= link_to "Редактировать", edit_admin_section_path(section), class: "btn btn-warning" %>
          <%= link_to "Удалить", admin_section_path(section), method: :delete, class: "btn btn-danger" %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to "Создать", new_admin_section_path, class: "btn" %>

app/views/admin/sections/new.html.erb
<h1>Добавить раздел</h1>

<%= form_for @section, :as => :section, :url => admin_sections_path, :method => :post, html: {class: "form-horizontal"} do |f| %>

  <%= render 'form', section: @section, f: f %>

  <div class="control-group">
    <div class="controls">
      <%= f.submit "Создать", class: "btn" %>
    </div>
  </div>
<% end %>

app/views/admin/users/create.html.erb
<h1>Admin::Users#create</h1>
<p>Find me in app/views/admin/users/create.html.erb</p>

app/views/admin/users/destroy.html.erb
<h1>Admin::Users#destroy</h1>
<p>Find me in app/views/admin/users/destroy.html.erb</p>

app/views/admin/users/index.html.erb
<h1>Пользователи</h1>

<table class="table table-bordered">
  <thead>
    <tr>
      <th>E-mail</th>
      <th>Действие</th>
    </tr>
  </thead>
  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.email %></td>
        <td><%= link_to "Удалить", admin_user_path(user), method: :delete, class: "btn btn-danger" %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to "Создать", new_admin_user_path, class: "btn" %>

app/views/admin/users/new.html.erb
<h1>Создать пользователя</h1>

<%= form_for @user, html: {class: "form-horizontal"} do |f| %>
  <div class="control-group">
    <%= f.label :email, class: "control-label" %>
    <div class="controls">
      <%= f.text_field :email %>
    </div>
  </div>

  <div class="control-group">
    <%= f.label :password, class: "control-label" %>
    <div class="controls">
      <%= f.password_field :password %>
    </div>
  </div>

  <div class="control-group">
    <div class="controls">
      <%= f.submit "Создать", class: "btn" %>
    </div>
  </div>
<% end %>

app/views/main/index.html.erb
<h1>Добро пожаловать на Дельта-Чан</h1>

<h2>Свежие треды</h2>

<% @topics.each do |topic| %>
  <%= render 'sections/topic', topic: topic, reply: false %>
  <hr/>
<% end %>

app/views/messages/_form.html.erb
<%= form_for message, html: {class: "form-horizontal", multipart: true} do |f| %>
  <%= f.hidden_field :topic_id %>

  <% message.errors.full_messages.each do |msg| %>
    <div class="alert alert-error"><%= msg %></span></div>
  <% end %>

  <fieldset>
    <legend>Написать в тред</legend>

    <div class="row">

      <div class="span4">
        <%= f.label :author %>
        <%= f.text_field :author, class: "message-input" %>
      </div>

      <div class="span4">
        <%= f.label :image %>
        <%= f.file_field :image %>
      </div>

      <div class="span4">
        <%= f.label :image_url %>
        <%= text_field_tag :image_url, params[:image_url] %>
      </div>
    </div>

    <div class="row">
      <div class="span12">
        <%= f.label :message %>
        <%= f.text_area :message, rows: "5", class: "message-textarea" %>
      </div>
    </div>

    <div class="row">
      <div class="span12">
        <%= f.submit "Написать", class: "btn" %>
      </div>
    </div>
  </fieldset>
<% end %>

app/views/messages/create.html.erb
<h1>Messages#create</h1>
<p>Find me in app/views/messages/create.html.erb</p>

app/views/messages/new.html.erb
<%= render 'form', message: @message %>

app/views/messages/show.html.erb
<h1>Messages#show</h1>
<p>Find me in app/views/messages/show.html.erb</p>

app/views/sections/_message.html.erb
<div class="row message offset1">
  <div class="message-caption span10">
    Author: <strong><%= message.author %></strong>, <strong>№ <%= message.id %></strong>
  </div>
  <% if message.image.exists? %>
    <div class="span3 image"><%= link_to image_tag(message.image.url(:thumb)), message.image.url %></div>
    <div class="span7 message"><%= simple_format(auto_link(message.message)) %></div>
  <% else %>
    <div class="span10 message"><%= simple_format(auto_link(message.message)) %></div>
  <% end %>
</div>

app/views/sections/_new_topic.html.erb
<%= form_for @topic, url: section_topics_path(@topic.section.slug), html: {class: "form-horizontal", multipart: true} do |f| %>
  <%= f.hidden_field :section_id %>

  <% @topic.errors.full_messages.each do |msg| %>
    <div class="alert alert-error"><%= msg %></span></div>
  <% end %>

  <fieldset>
    <legend>Создать тред</legend>

    <div class="row">
      <div class="span4">
        <%= f.label :title %>
        <%= f.text_field :title, class: "message-input" %>
      </div>

      <div class="span4">
        <%= f.label :author %>
        <%= f.text_field :author, class: "message-input" %>
      </div>

      <div class="span4">
        <%= f.label :image %>
        <%= f.file_field :image %>
      </div>
    </div>

    <div class="row">
      <div class="span12">
        <%= f.label :image_url %>
        <%= text_field_tag :image_url, params[:image_url], class: "input-xxlarge" %>
      </div>
    </div>

    <div class="row">
      <div class="span12">
        <%= f.label :message %>
        <%= f.text_area :message, rows: "5", class: "message-textarea" %>
      </div>
    </div>

    <div class="row">
      <div class="span12">
        <%= f.submit "Создать", class: "btn" %>
      </div>
    </div>
  </fieldset>
<% end %>

app/views/sections/_topic.html.erb
<div class="row topic">
  <div class="topic-caption span12">
    Author: <strong><%= topic.author %></strong>,
    Title: <strong><%= topic.title %></strong>,
    <strong>№ <%= topic.id %></strong>,
    <%= link_to "# [комментариев: #{topic.messages.count}]", section_topic_path(topic.section.slug, topic) %>
  </div>
  <% if topic.image.exists? %>
    <div class="span3 image"><%= link_to image_tag(topic.image.url(:thumb)), topic.image.url %></div>
    <div class="span8 message"><%= simple_format(auto_link(topic.message)) %></div>
  <% else %>
    <div class="span12 message"><%= simple_format(auto_link(topic.message)) %></div>
  <% end %>
  <% if reply %>
    <div class="topic-footer span12">
      <%= link_to "Ответить", section_topic_path(topic.section.slug, topic) %>
    </div>
  <% end %>
</div>

app/views/sections/index.html.erb
<h1>Sections#index</h1>
<p>Find me in app/views/sections/index.html.erb</p>

app/views/sections/show.html.erb
<div class="row">
  <h1><%= @section.title %></h1>
  <p><%= @section.description %></p>
</div>

<div class="row">
  <%= render 'new_topic' %>
</div>

<% @topics.each do |topic| %>
  <%= render 'topic', topic: topic, reply: true %>
  <% if topic.messages.count > 3 %>
    <div class="row">
      <div class="span12"><i>Чтобы посмотреть еще <%= topic.messages.count-3 %> комментариев, нажмите "Ответить"</i></div>
    </div>
  <% end %>
  <% topic.messages.last(3).each do |message| %>
    <%= render 'message', message: message %>
  <% end %>
<% end %>

app/views/topics/_message.html.erb
<div class="row message">
  <div class="message-caption span12">
    Author: <strong><%= message.author %></strong>, <strong>№ <%= message.id %></strong>
  </div>
  <% if message.image.exists? %>
    <div class="span3 image"><%= link_to image_tag(message.image.url(:thumb)), message.image.url %></div>
    <div class="span8 message"><%= simple_format(auto_link(message.message)) %></div>
  <% else %>
    <div class="span12 message"><%= simple_format(auto_link(message.message)) %></div>
  <% end %>
</div>

app/views/topics/create.html.erb
<h1>Topics#create</h1>
<p>Find me in app/views/topics/create.html.erb</p>

app/views/topics/show.html.erb
<div class="row"><h1>Просмотр <%= @topic.title %></h1></div>

<div class="row"><%= render 'messages/form', message: @message %></div>

<%= render 'sections/topic', topic: @topic, reply: false %>

<% @topic.messages.each do |message| %>
  <%= render 'message', message: message %>
<% end %>