config/routes.rb
DeltaChan::Application.routes.draw do

  namespace :admin do
    root to: "dashboard#index"
    resource :session, only: [:new, :create, :destroy]
    resources :users, only: [:new, :create, :destroy, :index]
    resources :sections
  end

  root to: "main#index"

  resources :messages, only: [:show, :create]

  resources :sections, path: '', only: [:show] do
    resources :topics, only: [:show, :create]
  end

end

app/models/admin_user.rb
class AdminUser < ActiveRecord::Base
  has_secure_password
  attr_accessible :email, :password

  validates_presence_of :email
  validates_uniqueness_of :email
end

app/models/message.rb
class Message < ActiveRecord::Base
  belongs_to :topic
  attr_accessible :author, :image, :message, :topic, :topic_id

  has_attached_file :image, :styles => { :thumb => "200x200>" }

  validates :message, :presence => true
  validates :topic_id, :numericality => { :only_integer => true }

  default_scope order('created_at ASC')
end

app/models/section.rb
class Section < ActiveRecord::Base
  attr_accessible :description, :position, :slug, :title

  validates :description, :slug, :title, :presence => true
  validates :position, :numericality => { :only_integer => true }
end

app/models/topic.rb
class Topic < ActiveRecord::Base
  belongs_to :section
  has_many :messages
  attr_accessible :author, :message, :title, :image, :section_id
  has_attached_file :image, :styles => { :thumb => "200x200>" }

  validates :message, :title, :presence => true
  validates :section_id, :numericality => { :only_integer => true }

  default_scope order('created_at DESC')
end

app/controllers/admin/sections_controller.rb
class Admin::SectionsController < Admin::DashboardController
  crudify :section

  def create
    @section = Section.new(params[:section])
    if @section.save
      flash[:notice] = "Section created"
      redirect_to admin_sections_path
    else
      render 'new'
    end
  end
end

app/controllers/admin/users_controller.rb
class Admin::UsersController < Admin::DashboardController
  def index
    @users = AdminUser.all
  end

  def new
    @user = AdminUser.new
  end

  def create
    @user = AdminUser.new(params[:admin_user])
    if @user.save
      redirect_to admin_users_path
    else
      flash[:notice] = "Error saving user"
      redirect_to admin_users_path
    end
  end

  def destroy
    AdminUser.find(params[:id]).destroy
    flash[:notice] = "User destroyed"
    redirect_to admin_users_path
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery

  private

  def current_user
    begin
      @current_user ||= AdminUser.find(session[:user_id]) if session[:user_id]
    rescue
      nil
    end
  end

  def check_auth
    redirect_to new_admin_session_path unless current_user
  end

  helper_method :current_user
end

app/controllers/main_controller.rb
class MainController < ApplicationController
  def index
    @topics = Topic.limit(25)
  end
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
  def create
    @message = Message.new(params[:message])
    unless params[:image_url].empty?
      begin
        @message.image = URI.parse(URI.encode(params[:image_url]))
      rescue
        flash[:notice] = "Loading image from url failed!"
      end
    end
    if @message.save
      flash[:notice] = "Message created"
      redirect_to "/#{@message.topic.section.slug}/topics/#{@message.topic.id}"
    else
      render template: 'messages/new'
    end
  end

  def show
  end
end

app/controllers/sections_controller.rb
class SectionsController < ApplicationController

  def show
    @section = Section.find_by_slug(params[:id])
    @topic = Topic.new(section_id: @section.id)
    @topics = Topic.find_all_by_section_id(@section.id)
  end
end

app/controllers/topics_controller.rb
class TopicsController < ApplicationController

  def create
    @topic = Topic.new(params[:topic])
    unless params[:image_url].empty?
      begin
        @topic.image = URI.parse(URI.encode(params[:image_url]))
      rescue
        flash[:notice] = "Loading image from url failed!"
      end
    end
    if @topic.save
      flash[:notice] = "Topic created"
      redirect_to "/#{@topic.section.slug}"
    else
      @section = @topic.section
      render template: 'sections/show'
    end
  end

  def show
    @topic = Topic.find(params[:id])
    @message = Message.new(topic: @topic)
  end
end

app/helpers/admin/dashboard_helper.rb
module Admin::DashboardHelper
end

app/helpers/admin/sections_helper.rb
module Admin::SectionsHelper
end

app/helpers/admin/sessions_helper.rb
module Admin::SessionsHelper
end

app/helpers/admin/users_helper.rb
module Admin::UsersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper

  def sections
    Section.all
  end
end

app/helpers/main_helper.rb
module MainHelper
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/helpers/sections_helper.rb
module SectionsHelper
end

app/helpers/topics_helper.rb
module TopicsHelper
end

app/views/layouts/admin.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Delta-Chan Admin: Linux-related stuff chan</title>
  <meta charset="utf-8">
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<div class="navbar navbar-fixed-top">
  <div class="navbar-inner">
    <div class="container">
      <a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </a>
      <a class="brand" href="/">Delta-Chan</a>
      <div class="nav-collapse collapse">
        <ul class="nav">
          <li><%= link_to "Главная", admin_root_path %></li>
          <li><%= link_to "Пользователи", admin_users_path %></li>
          <li><%= link_to "Разделы", admin_sections_path %></li>
          <li><%= link_to "Выйти", admin_session_path, method: :delete %></li>
        </ul>
      </div><!--/.nav-collapse -->
    </div>
  </div>
</div>

<div class="container">
  <% if notice %><p class="alert alert-info"><%= notice %></p><% end %>
  <% if alert %><p class="alert"><%= alert %></p><% end %>

  <%= yield %>

</div> <!-- /container -->

</body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Delta-Chan: Linux-related stuff chan</title>
  <meta charset="utf-8">
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<div class="navbar navbar-fixed-top">
  <div class="navbar-inner">
    <div class="container">
      <a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </a>
      <a class="brand" href="/">Delta-Chan</a>
      <div class="nav-collapse collapse">
        <ul class="nav">
          <li><%= link_to "/", root_path %></li>
          <% sections.each do |section| %>
            <li><%= link_to "/#{section.slug}", "/#{section.slug}", title: section.title %></li>
          <% end %>
        </ul>
      </div><!--/.nav-collapse -->
    </div>
  </div>
</div>

<div class="container">
  <% if notice %>
    <script>
      $(document).ready(function() {
        setTimeout(function() { $(".alert-info").hide('slow') }, 3000)
      })
    </script>
    <p class="alert alert-info"><%= notice %></p>
  <% end %>
  <% if alert %>
    <script>
      $(document).ready(function() {
        setTimeout(function() { $(".alert-alert").hide('slow') }, 3000)
      })
    </script>
    <p class="alert alert-alert"><%= alert %></p>
  <% end %>

  <%= yield %>

</div> <!-- /container -->

<footer class="footer">
      <div class="container">
        <p>Все права и копирайты на этой странице принадлежат правообладателям. За любую размещенную информацию несет личную ответственность постер (лицо, загрузившее эту информацию). Все комментарии принадлежат лицам, отправившим их.</p>
        <p>Если вы обнаружили информацию, размещённую против правил, пожалуйста, <a href="mailto:abuse@delta-zet.com">сообщите нам об этом.</a></p>
        <ul class="footer-links">
          <li><a href="http://delta-zet.com/">Delta Zet llc.</a></li>
          <li class="muted">·</li>
          <li><a href="https://linux.org.ru/">Linux.Org.Ru</a></li>
          <li class="muted">·</li>
          <li><a href="https://github.com/Delta-Zet/delta-chan">Исходники</a></li>
        </ul>
      </div>
    </footer>

</body>
</html>